#!/bin/bash


java -jar ~/Downloads/apache-ivy-2.4.0/ivy-2.4.0.jar \
  -debug \
  -settings ivysettings.xml \
  -ivy ivy.xml \
  -publish main \
  -publishpattern "[artifact]-[revision]-[type].[ext]" \
  -revision 1.0.0 \
  -overwrite

#  -status released

